---
all:
  children:
    etcd:
      hosts:
        node1:
          ansible_host: 192.168.68.130
          ip: 192.168.68.130
          access_ip: 192.168.68.130
        node2:
          ansible_host: 192.168.68.131
          ip: 192.168.68.131
          access_ip: 192.168.68.131
        node3:
          ansible_host: 192.168.68.132
          ip: 192.168.68.132
          access_ip: 192.168.68.132
    k8s_cluster:
      children:
        kube_control_plane:
          hosts:
            node1: {}
            node2: {}
        kube_node:
          hosts:
            node1: {}
            node2: {}
            node3: {}
