all:
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
    node_exporter_basic_auth_users:
      adam: qqq111
  hosts:
    thor:
      ansible_host: 192.168.68.130
      ip: 192.168.68.130
      access_ip: 192.168.68.130
    kube2:
      ansible_host: 192.168.68.131
      ip: 192.168.68.131
      access_ip: 192.168.68.131
    kube3:
      ansible_host: 192.168.68.132
      ip: 192.168.68.132
      access_ip: 192.168.68.132
  children:
    kube_control_plane:
      hosts:
        thor:
        kube2:
        kube3:
    kube_node:
      hosts:
        thor:
        kube2:
        kube3:
    etcd:
      hosts:
        thor:
        kube2:
        kube3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
